# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KYGcSJmfSjSUZ1CqeJDSTUI6tuP49WTH
"""

per1 = input('Введите путь к файлу file_task4.txt: ')

import math

with open(per1, "r") as f:
      nums = list(map(float, f.read().split()))
      # print(nums)

# nums = [1, 10, 2, 9]
result_digit = math.ceil((max(nums))/2)
count = 0
for id, i in enumerate(nums):
    while i != result_digit:
         if i < result_digit:
             i += 1
             count += 1
         elif i > result_digit:
              i -= 1
              count += 1
         else:
            nums[id] = i
print(count)

